#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
# To update the package lists
sudo apt-get update

# To install the HAProxy
sudo apt-get install haproxy -y

# To configure the HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.26.225.174:80 check
    server web-02 18.209.224.170:80 check
EOT

# To test the HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# To start the HAProxy
sudo systemctl start haproxy

# To enable the HAProxy to start on boot
sudo systemctl enable haproxy
