#!/usr/bin/env bash
# This script should loop from 1 to 10 displaying bad luck for the 4th loop iteration, good luck for the 8th loop iteration, and Best School for the other iterations.

a=1

while [ $a -le 10 ]
do
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	a=$((a+1))
done
