#!/usr/bin/env bash
#Bash script that displays the numbers 1 to 20 outputing bad luck from China for the 4th loop iteration after displaying 4, outputing  bad luck from Japan for the 9th loop iteration after displaying 9, outputing bad luck from Italy for the 17th loop iteration after displaying 17.
a=1

while [ $a -le 20 ]
do
	case $a in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo $a
			;;
	esac
	a=$((a+1))
done
