#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory In a list format Where only the part of the name after the first dash is displayed.

for file in *
do
	if [ "${file:0:1}" != "." ] # ignore hidden files
	then
		name=${file#*-} # extract the part after the first dash
		echo "$name"
	fi
done
