#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# Install necessary packages
apt-get update
apt-get install -y dnsmasq

# Configure dnsmasq
echo "address=/localhost/127.0.0.2" >> /etc/dnsmasq.conf
echo "server=/facebook.com/8.8.8.8" >> /etc/dnsmasq.conf

# Restart dnsmasq
systemctl restart dnsmasq.service
